#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

mounts:
  - ["/dev/datavg/datalv", "/srv/docker-volumes"]

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose
  - systemctl start docker
  - systemctl enable docker
  - usermod -a -G docker vincent
  - mkdir /srv/docker-volumes
  - mount /dev/datavg/datalv /srv/docker-volumes
  - git clone https://github.com/vmisson/cloud-stack.git /srv/stack
  - docker network create docker
  - docker-compose  --file /srv/stack/core/docker-compose.yml up --detach
  - docker-compose  --file /srv/stack/apps/bitwarden/docker-compose.yml up --detach
  - docker-compose  --file /srv/stack/apps/mail/docker-compose.yml up --detach  
  - docker-compose  --file /srv/stack/apps/nextcloud/docker-compose.yml up --detach
  - docker-compose  --file /srv/stack/apps/freshrss/docker-compose.yml up --detach
  - docker-compose  --file /srv/stack/apps/prometheus/docker-compose.yml up --detach
  - docker-compose  --file /srv/stack/apps/statping/docker-compose.yml up --detach